"""initial alert and case models

Revision ID: b1218046b63f
Revises: 
Create Date: 2026-09-24 20:55:57.029627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1218046b63f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wazuh_alert_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('agent_name', sa.String(length=128), nullable=True),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_level', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('src_ip', sa.String(length=64), nullable=True),
    sa.Column('dst_ip', sa.String(length=64), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('decoder', sa.String(length=64), nullable=True),
    sa.Column('mitre_tactics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mitre_techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_alert', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_agent_id'), 'alerts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_alerts_agent_name'), 'alerts', ['agent_name'], unique=False)
    op.create_index(op.f('ix_alerts_dst_ip'), 'alerts', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_rule_level'), 'alerts', ['rule_level'], unique=False)
    op.create_index(op.f('ix_alerts_src_ip'), 'alerts', ['src_ip'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_alerts_wazuh_alert_id'), 'alerts', ['wazuh_alert_id'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_severity'), 'cases', ['severity'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_title'), 'cases', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_title'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_severity'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_alerts_wazuh_alert_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_src_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_level'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dst_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_agent_name'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_agent_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
